In [61]:
from sklearn.model_selection import train_test_split as sk_train_test_split
import numpy as np

from pprint import pprint

In [231]:
def train_test_split(*arrays, test_size=.25, shuffle=True):
    n = len(arrays[0])
    order = np.random.permutation(n) if shuffle else np.arange(n)
    k = int(np.ceil(n * test_size))
    order_train = order[:-k]
    order_test = order[-k:]
    l = []
    for i in arrays:
        l.append(i[order_train])
        l.append(i[order_test])
    pprint(locals())
    return l

In [232]:
X = np.arange(20).reshape((-1, 2))
y = np.sum(X, axis=1)
print(X)
print(y)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]
[ 1  5  9 13 17 21 25 29 33 37]


In [239]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, shuffle=0, test_size=.4)

{'arrays': (array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]]),
            array([ 1,  5,  9, 13, 17, 21, 25, 29, 33, 37])),
 'i': array([ 1,  5,  9, 13, 17, 21, 25, 29, 33, 37]),
 'k': 4,
 'l': [array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]]),
       array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19]]),
       array([ 1,  5,  9, 13, 17, 21]),
       array([25, 29, 33, 37])],
 'n': 10,
 'order': array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 'order_test': array([6, 7, 8, 9]),
 'order_train': array([0, 1, 2, 3, 4, 5]),
 'shuffle': 0,
 'test_size': 0.4}


In [240]:
X_train

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [241]:
y_train

array([ 1,  5,  9, 13, 17, 21])

In [242]:
X_test

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [243]:
y_test

array([25, 29, 33, 37])

In [244]:
train_test_split(np.array(range(5))
                , shuffle=False)

{'arrays': (array([0, 1, 2, 3, 4]),),
 'i': array([0, 1, 2, 3, 4]),
 'k': 2,
 'l': [array([0, 1, 2]), array([3, 4])],
 'n': 5,
 'order': array([0, 1, 2, 3, 4]),
 'order_test': array([3, 4]),
 'order_train': array([0, 1, 2]),
 'shuffle': False,
 'test_size': 0.25}


[array([0, 1, 2]), array([3, 4])]